# This is a basic workflow to help you get started with Actions

name: Create branch release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      Branch:
        description: 'Branch name on which jobs will be executed'
        required: true
        default: 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: PavloGomeniuk/Bakery
          ref: ${{ github.event.inputs.Branch }}
          fetch-depth: '0'
 
      # Runs a single command using the runners shell
      - name: Run a git script
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          #git rev-parse --verify --quiet main
          #echo $?
          RESULT = "git --version"
          echo $RESULT
          git checkout -b releases/v1
          #git commit -a -m "prod dependencies"
          #git push origin releases/v1

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
