name: Subworkflow
on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment name on which you want to make change'
        required: true
        type: choice
        default: 'dev'
        options: 
        - dev
        - demo
        - qa
        - prod
      Branch:
        description: 'Branch name on which jobs will be executed'
        required: true
        default: 'master'
      HSC-BE:
        description: 'Enter tag that you need to change not tag is'
        required: false
        default: 'v1'
        type: string
        
jobs:
  build:
    if: github.event.inputs.HSC-BE != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: PavloGomeniuk/BlogIn
          ref: ${{ github.event.inputs.Branch }}
          fetch-depth: '0'
      - name: installAdditionalSoftware
        run: |
          sudo apt-get update
          pip install --upgrade pip
          pip3 install git+https://github.com/python-semver/python-semver.git@3.0.0-dev.3
          pip install bumpversion
          wget -cq https://get.helm.sh/helm-v3.8.2-linux-amd64.tar.gz -O - | tar -xz
          mv linux-amd64/helm /usr/local/bin/helm && rm -r linux-amd64
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.24.4/yq_linux_amd64 && chmod a+x /usr/local/bin/yq

      - name: updateHscHelmChart
        env:
          TAG: ${{ github.event.inputs.HSC-BE }}
        run: |
          yq '.hsc-be.image.tag = env(TAG)' "environments/${{ github.event.inputs.Environment }}/hsc-be-proxy/values.yaml" > values.yaml.new
          #ls -la
          cat values.yaml.new
          yq '.' "environments/${{ github.event.inputs.Environment }}/hsc-be-proxy/values.yaml" > values.yaml.noblanks
          ls -la
          diff -B values.yaml.noblanks values.yaml.new > patch.file
          cat patch.file
          patch --ignore-whitespace "environments/${{ github.event.inputs.Environment }}/hsc-be-proxy/values.yaml" patch.file
          rm -f values.yaml.* patch.file
          ls -la
