name: Matrix
on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment name on which you want to make change'
        required: true
        type: choice
        default: 'dev'
        options: 
        - dev
        - demo
        - qa
        - prod
      Branch:
        description: 'Branch name on which jobs will be executed'
        required: true
        default: 'master'
      Hsc-be:
        description: 'Enter hsc-be tag that you need to change'
        required: false
        type: string
      Hsc-fe:
        description: 'Enter hsc-fe tag that you need to change'
        required: false
        type: string
      Hsc-fe-admin:
        description: 'Enter hsc-fe-admin tag that you need to change'
        required: false
        type: string
      Hsc-spec-public:
        description: 'Enter hsc-spec-public tag that you need to change'
        required: false
        type: string
      Hsc-spec-internal:
        description: 'Enter hsc-spec-internal tag that you need to change'
        required: false
        type: string
        
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          matrix="{\"services\":[{\"service\":\"hsc-be\",\"tag\":\"${{ github.event.inputs.Hsc-be }}\"},{\"service\":\"hsc-fe\",\"tag\":\"${{ github.event.inputs.Hsc-fe }}\"},{\"service\":\"hsc-fe-admin\",\"tag\":\"${{ github.event.inputs.Hsc-fe-admin }}\"},{\"service\":\"hsc-spec-public\",\"tag\":\"${{ github.event.inputs.Hsc-spec-public}}\"},{\"service\":\"hsc-spec-internal\",\"tag\":\"${{ github.event.inputs.Hsc-spec-internal}}\"}]}"
          echo $matrix 
          echo $matrix | jq .
          echo "::set-output name=matrix::$matrix | jq ."
          
  build:
    needs: matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}
    name: ${{matrix.services.service}}
    runs-on: ubuntu-latest
    #if: ${{matrix.services.tag}} != ''
    steps:
      - name: Check job
        if: matrix.services.tag == ''
        run: |
          echo "${{matrix.services.service}} ${{matrix.services.tag}}"
          exit 1
      - uses: actions/checkout@v3
        with:
          repository: PavloGomeniuk/BlogIn
          ref: ${{ github.event.inputs.Branch }}
          fetch-depth: '0'
      - name: installAdditionalSoftware
        #if: matrix.services.tag != ''
        run: |
          echo "${{matrix.services.service}} ${{matrix.services.tag}}"
 

    
