name: Matrix
on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment name on which you want to make change'
        required: true
        type: choice
        default: 'dev'
        options: 
        - dev
        - demo
        - qa
        - prod
      Branch:
        description: 'Branch name on which jobs will be executed'
        required: true
        default: 'master'
      HSC-BE:
        description: 'Enter tag that you need to change not tag is'
        required: false
        #default: 'v1'
        type: string
      HSC-FE:
        description: 'Enter tag that you need to change not tag is'
        required: false
        #default: 'v2'
        type: string
      HSC-KE:
        description: 'Enter tag that you need to change not tag is'
        required: false
        #default: 'v3'
        type: string
        
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          matrix="{\"services\":[{\"service\":\"hsc-be\",\"tag\":\"${{ github.event.inputs.HSC-BE }}\"},{\"service\":\"hsc-fe\",\"tag\":\"${{ github.event.inputs.HSC-FE }}\"},{\"service\":\"hsc-ke\",\"tag\":\"${{ github.event.inputs.HSC-KE }}\"}]}"
          echo $matrix 
          echo $matrix | jq .
          echo "::set-output name=matrix::$matrix | jq ."
          
  build:
    needs: matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}
    if: ${{matrix.services.tag}} != ''
    #name: Run ${{ join(matrix.*, ' - ') }} - ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: PavloGomeniuk/BlogIn
          ref: ${{ github.event.inputs.Branch }}
          fetch-depth: '0'
      - name: installAdditionalSoftware
        run: |
          echo "${{matrix.services.service}} ${{matrix.services.tag}}"
 

    
