name: Matrix
on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment name on which you want to make change'
        required: true
        type: choice
        default: 'dev'
        options: 
        - dev
        - demo
        - qa
        - prod
      Branch:
        description: 'Branch name on which jobs will be executed'
        required: true
        default: 'master'
      HSC-BE:
        description: 'Enter tag that you need to change not tag is'
        required: false
        default: 'v1'
        type: string
      HSC-FE:
        description: 'Enter tag that you need to change not tag is'
        required: false
        default: 'v1'
        type: string
        
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2

      - id: set-matrix
        run: |
          matrix="{"services":{"hsc-be":${{ github.event.inputs.HSC-BE }},"hsc-fe":${{ github.event.inputs.HSC-FE }}}}"
          echo $matrix
          echo $matrix | jq .
          echo "::set-output name=matrix::$matrix"
          
  check-matrix:
    runs-on: ubuntu-latest
    needs: matrix
    steps:
      - name: Install json2yaml
        run: |
          sudo npm install -g json2yaml

      - name: Check matrix definition
        run: |
          matrix='${{ needs.matrix.outputs.matrix }}'
          echo $matrix
          echo $matrix | jq .
          echo $matrix | json2yaml
  
  build:
    needs: matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}
    if: github.event.inputs.HSC-BE != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: PavloGomeniuk/BlogIn
          ref: ${{ github.event.inputs.Branch }}
          fetch-depth: '0'
      - name: installAdditionalSoftware
        run: |
          echo "hello"

  
